baseURL = 'http://inthebloom.github.io/'
languageCode = 'ja'
DefaultContentLanguage = "ja"
title = "InTheDayDream"
description = "InTheDayDream: InTheBloom's Website"
author = "InTheBloom"
publishDir = "docs"

theme = "simplog"
pagination.pagerSize = 15
summarylength = 0
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
timeZone = "Asia/Tokyo"
googleAnalytics = ""
disqusShortname = ""


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 5

[taxonomies]
  tag = "tags"
  archive = "archives"

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[params]
  subtitle = ""
  colorTheme = "default"
  description = ""
  twitter = "UU9782wsEdANDhp"
  customCSS = "/css/custom.css"
  adobeFontsKitId = ""
  headerImagePath = ""

  [params.enabled]
    comment = true
    summary = true
    toc = true
